namespace DuplicatiIndexer.Data.Entities;

/// <summary>
/// Represents a single query and its response within a session.
/// </summary>
public class QueryHistoryItem
{
    /// <summary>
    /// Gets or sets the unique identifier for the history item.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Gets or sets the identifier of the session this query belongs to.
    /// </summary>
    public Guid SessionId { get; set; }

    /// <summary>
    /// Gets or sets the original query text as entered by the user.
    /// </summary>
    public string OriginalQuery { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the condensed/standalone query used for RAG search.
    /// For the first query in a session, this will be the same as OriginalQuery.
    /// </summary>
    public string CondensedQuery { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the response/answer generated by the LLM.
    /// </summary>
    public string Response { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the timestamp when the query was made.
    /// </summary>
    public DateTimeOffset QueryTimestamp { get; set; }

    /// <summary>
    /// Gets or sets the timestamp when the response was generated.
    /// </summary>
    public DateTimeOffset ResponseTimestamp { get; set; }

    /// <summary>
    /// Gets or sets the reasoning insights, thoughts, and actions taken to arrive at the response.
    /// </summary>
    public List<QueryHistoryEvent> Events { get; set; } = new();
}
